name: Trigger Enterprise Workflow on Release or Merge

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  trigger-enterprise-workflow:
    runs-on: ubuntu-latest
   # if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: weaveworks/weave-gitops-enterprise
          event-type: create-pr
